### ISSUE TITLE
1.0.5.4 .NET Error on Win 10

### ISSUE THREAD

**Issue by elpollitodiablo** [Ugleh/redditwallpaperchanger#1]
I know this is in german but it might help anyway

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

*************\* Ausnahmetext **************
System.ArgumentOutOfRangeException: "minValue" kann nicht größer als maxValue sein.
Parametername: minValue
   bei System.Random.Next(Int32 minValue, Int32 maxValue)
   bei Reddit_Wallpaper_Changer.Form1.setWallpaper(String url, String title, String threadID)
   bei Reddit_Wallpaper_Changer.Form1.changeWallpaper()
   bei Reddit_Wallpaper_Changer.Form1.changeWallpaperTimer_Tick(Object sender, EventArgs e)
   bei System.Windows.Forms.Timer.OnTick(EventArgs e)
   bei System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.96.0 built by: NETFXREL2STAGE.
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.

Reddit Wallpaper Changer
    Assembly-Version: 1.0.5.4.
    Win32-Version: 1.0.5.4.
##     CodeBase: file:///D:/Program%20Files%20(x86)/Reddit%20Wallpaper%20Changer/Reddit%20Wallpaper%20Changer.exe.

System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.

System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.

System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.

System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.

System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.

System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.

System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.

System.Web
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll.

Newtonsoft.Json
    Assembly-Version: 4.5.0.0.
    Win32-Version: 4.5.11.15520.
##     CodeBase: file:///D:/Program%20Files%20(x86)/Reddit%20Wallpaper%20Changer/Newtonsoft.Json.DLL.

mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.

System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.

*************\* JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

**Comment by Ugleh** [comment]
It has to do with the randomize setting I guess. What was your settings looking like?

**Comment by elpollitodiablo** [comment]
updated to 1.0.5.7 and it seems to be working now :)

**Comment by Ugleh** [comment]
Thanks for the help reporting these bugs.
